name: "Test Build"

on:
  push:
    branches-ignore:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_FEATURE_FLAGS: "dependencygraph"

permissions:
  contents: "write"

jobs:
  publish:
    runs-on: "windows-latest"
    strategy:
      fail-fast: true
      matrix:
        build-config: ["Debug", "Release"]
        arch: ["x64", "x86"]
        path: ["*.dll *.pdb", "*.dll"]

    env:
      archive-path: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.build-config }}-${{ matrix.arch }}${{ contains(matrix.path, '.pdb') && '-WithDebugSymbols' || '' }}.zip

    name: "Build a ${{ matrix.build-config }} (${{ matrix.arch }} | ${{ matrix.path }}) version"
    steps:
      - name: "Export GitHub Actions cache environment variables"
        uses: "actions/github-script@main"
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: "Print Archive name"
        run: "echo ${{ env.archive-path }}"

      - name: "Checkout"
        uses: "actions/checkout@main"
        with:
          submodules: true

      - name: "Add MSBuild to PATH"
        uses: "microsoft/setup-msbuild@main"
        with:
          vs-prerelease: true

      - name: "Integrate vcpkg"
        run: "vcpkg integrate install"

      - name: "Build solution"
        run: "msbuild /m /p:Configuration=${{ matrix.build-config }} /property:Platform=${{ matrix.arch }}"

      - name: "Pack to archive"
        shell: "bash"
        run: |
            "cd bin"
            "zip -r ${{ env.archive-path }} . ${{ matrix.path }}"
            "unzip -l ${{ env.archive-path }}"
